import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { PrimeReactProvider } from "primereact/api";

import 'primeicons/primeicons.css';
        
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "primereact/resources/themes/lara-light-cyan/theme.css";
import "/node_modules/primeflex/primeflex.css";


export default function RootLayout({ children }) {
  return (
    <PrimeReactProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </PrimeReactProvider>
  );
}
